[workspace]
members = [
    "lib",
    "test-helpers",
    "contracts/cmtat-aztec",
    "contracts/cmtat-aztec-debt",
    "contracts/cmtat-aztec-light",
    "contracts/cmtat-aztec-auth",
    "contracts/cmtat-aztec-auth-multitoken",
]
default-member = "contracts/cmtat-aztec"
